### ISSUE TITLE
conda flextaxd not compatible

### ISSUE THREAD

**Issue by CarolineOhrman** [FOI-Bioinformatics/CanSNPer2#3]
When running CanSNPer2 you need to use the latest version of flextaxd from github -version of flextaxd https://github.com/FOI-Bioinformatics/flextaxd (not conda)

Flextaxd conda will be updated after some more bugtesting

```
python flextaxd/setup.py install
```

**Comment by druvus** [comment]
conda-version is now updated to 0.2.0.
