### ISSUE TITLE
add NEXT FREE SNP, B.316, to the F.tularensis database for publication

### ISSUE THREAD

**Issue by BigNianNGS** [FOI-Bioinformatics/CanSNPer2#42]
Dear CarolineOhrman，

    Using the CANSNPer software, I discovered SNP loci in the B.217 branch that can further distinguish CP012092 and CP007148. I would like to give them NEXT FREE SNP,  B.316, when publishing my article. Could you please let me know how to add them to the database for publication?

Kind regards

**Comment by CarolineOhrman** [comment]
Dear BigNianNGS, 

I am pleased to hear that you want to contribute with a new canSNP. We will reserve B.316 for you. Once the paper is published, the name will be verified. Before adding it to the scheme and prebuilt database, we will confirm its accuracy. If everything is correct, we will update the database accordingly.

If you want to create your own local database with your new snp you need to 

1. download the two source files [francisella_tularensis_snp.txt](https://github.com/FOI-Bioinformatics/CanSNPer2-data/blob/master/source/francisella_tularensis_snp.txt) and [francisella_tularensis_tree.txt](https://github.com/FOI-Bioinformatics/CanSNPer2-data/blob/master/source/francisella_tularensis_tree.txt) and add your canSNP in both these files
2. build your database following this instruction [quick-start-custom-databases](https://github.com/FOI-Bioinformatics/CanSNPer2?tab=readme-ov-file#quick-start-custom-databases)
3. Now you can run canSNPer as usual with this database

Please tell if you have more questions

Kind regards
Caroline
