### ISSUE TITLE
Output, export and --keep_temp when running --skip_mauve

### ISSUE THREAD

**Issue by CarolineOhrman** [FOI-Bioinformatics/CanSNPer2#5]
1. How I would like the output options to be 
- If no output options specified -> called cansnp (Final) to stdout. If --supress is specified nothing but the name of the file and the cansnp exv:
SCHUS4.fna A.II
FSC1005.fna NA
FSC200 B.265 
- --snpfile PREFIX ->  Outputs a _snpfile.txt (or maby just named _snp.txt) in CWD or --output dir
- --treefile PREFIX -> Outputs _CanSNP_tree.pdf (or maby just named _tree.pdf  in CWD or in --output dir
- --calledsnps -> _called_snps_snpfile.txt (or maby just named *_called.txt) is produced

2. What is PREFIX in --snpfile and --treefile (and other ouputs?) doing? Specify in help what it means. Could it be optional?

3. Remove export function. Not needed. 

4. Final cansnp is only promted to stdout for the last file 

4. If --skip_mauve is specified --keep_temp should automatically be TRUE

**Comment by davve2** [comment]
1. Output options are changed, one snpfile and one snpfile_called will be default but can supressed by using --no_export
CanSNPer will always output the Final SNP (or NA if none) and the filename at the end of each input. If this output is piped into a file it can be directly used as genome input file for flextaxd.
A tree pdf will be created if --save_tree is given, no prefix are allowed, the prefix of the input file will be used instead!
2,3,4,5 are also fixed, no PREFIX are allowed this will be fetched from input filename
