### ISSUE TITLE
Wrong output in "called_snps" file

### ISSUE THREAD

**Issue by CarolineOhrman** [FOI-Bioinformatics/CanSNPer2#7]
Calls SNP even if the SNPs are sporadic

[Francisella_adeliensis_FDC440_GCF003290445.1_called_snps_2020-03-03.txt](https://github.com/FOI-Bioinformatics/CanSNPer2/files/4282195/Francisella_adeliensis_FDC440_GCF003290445.1_called_snps_2020-03-03.txt)
[Francisella_adeliensis_FDC440_GCF003290445.1_CanSNP_tree.pdf](https://github.com/FOI-Bioinformatics/CanSNPer2/files/4282196/Francisella_adeliensis_FDC440_GCF003290445.1_CanSNP_tree.pdf)

**Comment by davve2** [comment]
This is handled in the latest update!
